import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, XAxis, YAxis } from "recharts";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Panel } from "./shared";
import type { ActivityPointDto } from "@/lib/types";
const cfg={answered:{label:"Answered",color:"var(--chart-success)"},completed:{label:"Completed",color:"var(--chart-info)"},failed:{label:"Failed",color:"var(--chart-error)"}};
const periods = [["24h","Last 24 hours"],["7d","7 days"],["30d","30 days"]] as const;
export function ActivityChart({ data }: { data: ActivityPointDto[] }){const [period,setPeriod]=useState<(typeof periods)[number][0]>("24h");return <Panel title="Call Activity" action={<div className="flex rounded-lg bg-muted p-1">{periods.map(([v,l])=><button key={v} onClick={()=>setPeriod(v)} className={`rounded-md px-2.5 py-1 text-[11px] font-medium ${period===v?"bg-card text-foreground shadow-xs":"text-muted-foreground"}`}>{l}</button>)}</div>}><ChartContainer config={cfg} className="h-[260px] w-full aspect-auto"><AreaChart data={data} margin={{left:-20,right:8,top:8}}><defs><linearGradient id="fillAnswered" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--color-answered)" stopOpacity={0.22}/><stop offset="95%" stopColor="var(--color-answered)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="time" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Area type="monotone" dataKey="answered" stroke="var(--color-answered)" fill="url(#fillAnswered)" strokeWidth={2}/><Area type="monotone" dataKey="completed" stroke="var(--color-completed)" fill="transparent" strokeWidth={2}/><Area type="monotone" dataKey="failed" stroke="var(--color-failed)" fill="transparent" strokeWidth={2}/></AreaChart></ChartContainer><div className="flex justify-center gap-5 text-xs">{Object.entries(cfg).map(([k,v])=><span key={k} className="flex items-center gap-2"><i className="size-2 rounded-full" style={{background:v.color}}/>{v.label}</span>)}</div></Panel>}
const perf=[{name:"Mon",calls:190},{name:"Tue",calls:245},{name:"Wed",calls:220},{name:"Thu",calls:285},{name:"Fri",calls:260},{name:"Sat",calls:170},{name:"Sun",calls:145}];
export function MiniBarChart({title="Calls Over Time"}:{title?:string}){return <Panel title={title}><ChartContainer config={{calls:{label:"Calls",color:"var(--chart-info)"}}} className="h-52 w-full aspect-auto"><BarChart data={perf}><CartesianGrid vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="calls" fill="var(--color-calls)" radius={[4,4,0,0]}/></BarChart></ChartContainer></Panel>}
const outcomes=[{name:"Completed",value:68,color:"var(--chart-success)"},{name:"Follow-up",value:18,color:"var(--chart-info)"},{name:"No answer",value:9,color:"var(--chart-warning)"},{name:"Failed",value:5,color:"var(--chart-error)"}];
export function OutcomeChart({title="Call Outcomes"}:{title?:string}){return <Panel title={title}><ChartContainer config={{}} className="h-52 w-full aspect-auto"><PieChart><Pie data={outcomes} dataKey="value" innerRadius={50} outerRadius={78} paddingAngle={3}>{outcomes.map(o=><Cell key={o.name} fill={o.color}/>)}</Pie><ChartTooltip content={<ChartTooltipContent/>}/></PieChart></ChartContainer><div className="grid grid-cols-2 gap-2 text-xs">{outcomes.map(o=><span key={o.name}><i className="mr-2 inline-block size-2 rounded-full" style={{background:o.color}}/>{o.name} {o.value}%</span>)}</div></Panel>}
